#!/usr/bin/env node
// Builds packages/ui/app (Preact) into ONE self-contained HTML document and
// writes it to src/generated/app-html.ts as a string constant.
//
// Why: same Bun --compile constraint as packages/rules/scripts/sync-bundle.mjs.
// The standalone binaries have no filesystem to read assets from, so the UI
// must be embedded as a module-level string. Node (npm) uses the same string,
// so there is exactly one code path.
//
// Run via: `prepare` (after pnpm install), `prepack` (before npm publish), and
// in CI before `bun build --compile`. Idempotent — writes only on change.

import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const UI_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_TS = join(UI_ROOT, "src", "generated", "app-html.ts");

// Published tarballs ship src/generated but not app/ or vite: nothing to build.
if (!existsSync(join(UI_ROOT, "app", "index.html"))) process.exit(0);

const { build } = await import("vite");
const outDir = mkdtempSync(join(tmpdir(), "hw-ui-"));
try {
  await build({
    root: join(UI_ROOT, "app"),
    logLevel: "warn",
    configFile: false,
    oxc: { jsx: { runtime: "automatic", importSource: "preact" } },
    build: {
      outDir,
      emptyOutDir: true,
      cssCodeSplit: false,
      assetsInlineLimit: Number.MAX_SAFE_INTEGER,
      modulePreload: false,
      rolldownOptions: { output: { codeSplitting: false } },
    },
  });

  let html = readFileSync(join(outDir, "index.html"), "utf-8");
  const assets = join(outDir, "assets");
  const files = existsSync(assets) ? readdirSync(assets) : [];
  for (const f of files) {
    const body = readFileSync(join(assets, f), "utf-8");
    if (f.endsWith(".js")) {
      const tag = new RegExp(`<script[^>]*src="[^"]*${escapeRe(f)}"[^>]*></script>`);
      // `</script` inside the bundle would close the inline tag early.
      html = html.replace(
        tag,
        () => `<script type="module">${body.replaceAll("</script", "<\\/script")}</script>`,
      );
    } else if (f.endsWith(".css")) {
      const tag = new RegExp(`<link[^>]*href="[^"]*${escapeRe(f)}"[^>]*>`);
      html = html.replace(tag, () => `<style>${body}</style>`);
    }
  }
  if (/\s(src|href)="\/?assets\//.test(html)) {
    throw new Error("build-app: an asset was not inlined; the binary would serve a broken page");
  }

  const next = `// GENERATED by packages/ui/scripts/build-app.mjs — do not edit.\nexport const APP_HTML: string = ${JSON.stringify(html)};\n`;
  const prev = existsSync(OUT_TS) ? readFileSync(OUT_TS, "utf-8") : "";
  if (prev !== next) writeFileSync(OUT_TS, next);
  console.log(
    `ui: app-html.ts ${prev === next ? "unchanged" : "written"} (${(html.length / 1024).toFixed(1)} KB)`,
  );
} finally {
  rmSync(outDir, { recursive: true, force: true });
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
