#!/usr/bin/env node
// Generates packages/rules/src/version.ts from packages/rules/package.json.
//
// Why: same Bun --compile gotcha as packages/cli — reading package.json at
// runtime via fs.readFileSync(import.meta.url-relative path) fails inside
// Bun's virtual /$bunfs/ filesystem. Generating a TS constant at install/
// publish/CI time bakes the literal into the bundled output.
//
// Run via: `prepare` script (after pnpm install) AND `prepack` (before npm
// publish) AND in CI before `bun build --compile` (release-binaries.yml).
// Idempotent — overwrites only if version changes.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RULES_ROOT = join(__dirname, "..");
const PKG_PATH = join(RULES_ROOT, "package.json");
const VERSION_TS_PATH = join(RULES_ROOT, "src", "version.ts");

const { version } = JSON.parse(readFileSync(PKG_PATH, "utf8"));

const banner =
  "// Generated by scripts/sync-version.mjs — do NOT edit by hand.\n// Source of truth: packages/rules/package.json#version (Changesets-managed).\n";
const body = `export const RULES_PACK_VERSION = ${JSON.stringify(version)};\n`;
const next = banner + body;

let current = "";
try {
  current = readFileSync(VERSION_TS_PATH, "utf8");
} catch {
  // First run — file does not exist yet.
}

if (current !== next) {
  writeFileSync(VERSION_TS_PATH, next);
}
// Silent on success — runs on every install.
