#!/usr/bin/env node
// Generates packages/mcp/src/version.ts AND keeps packages/mcp/server.json
// in lockstep with packages/mcp/package.json#version.
//
// Why src/version.ts: The MCP server exposes its version in the MCP
// `initialize` server-info payload and in the `--version` flag of the
// single-bin dispatcher. Reading `package.json` at runtime works under Node
// + npm but is fragile across resolution layouts (pnpm hoisting, npx temp
// dirs, the bundled tarball). Generating a TS constant at build time bakes
// the literal into the dist output — no runtime branching, no
// JSON-import-attribute gymnastics.
//
// Why server.json: The MCP registry server.json carries the canonical
// package version in two places (top-level `version` + `packages[0].version`).
// Both must equal package.json#version or `mcp-publisher publish` rejects
// the upload AND tests/integration/manifest-consistency.test.ts trips at
// preflight. Without auto-sync, every Changesets-driven version bump
// requires a manual server.json edit — exactly the drift class this
// drift-gate exists to prevent.
//
// Run via: `prepare` script (after pnpm install) AND `prepack` (before npm
// publish). Idempotent — overwrites only if version changes.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MCP_ROOT = join(__dirname, "..");
const PKG_PATH = join(MCP_ROOT, "package.json");
const VERSION_TS_PATH = join(MCP_ROOT, "src", "version.ts");
const SERVER_JSON_PATH = join(MCP_ROOT, "server.json");

// src/ may not exist yet on first install — sibling CLI script gets away
// without mkdir because packages/cli/src/ pre-exists. Make this self-sufficient.
mkdirSync(dirname(VERSION_TS_PATH), { recursive: true });

const { version } = JSON.parse(readFileSync(PKG_PATH, "utf8"));

// 1. src/version.ts — TS constant.
const banner =
  "// Generated by scripts/sync-version.mjs — do NOT edit by hand.\n// Source of truth: packages/mcp/package.json#version (Changesets-managed).\n";
const body = `export const VERSION = ${JSON.stringify(version)};\n`;
const next = banner + body;

let current = "";
try {
  current = readFileSync(VERSION_TS_PATH, "utf8");
} catch {
  // First run — file does not exist yet.
}

if (current !== next) {
  writeFileSync(VERSION_TS_PATH, next);
}

// 2. server.json — top-level `version` + `packages[0].version`. Both fields
// MUST equal package.json#version (manifest-consistency.test.ts gate). Write
// only on drift to avoid touching mtime on every install.
const serverJsonRaw = readFileSync(SERVER_JSON_PATH, "utf8");
const serverJson = JSON.parse(serverJsonRaw);
let serverJsonDirty = false;
if (serverJson.version !== version) {
  serverJson.version = version;
  serverJsonDirty = true;
}
if (Array.isArray(serverJson.packages) && serverJson.packages[0] != null) {
  if (serverJson.packages[0].version !== version) {
    serverJson.packages[0].version = version;
    serverJsonDirty = true;
  }
}
if (serverJsonDirty) {
  // Preserve trailing newline + 2-space indent (matches the hand-authored shape).
  writeFileSync(SERVER_JSON_PATH, `${JSON.stringify(serverJson, null, 2)}\n`);
}
// Silent on success — runs on every install. Failure path would use
// console.error (writeFileSync throws and the process exits non-zero).
