#!/usr/bin/env node
// Generates packages/mcp/src/version.ts from packages/mcp/package.json.
//
// Why: The MCP server exposes its version in the MCP `initialize` server-info
// payload and in the `--version` flag of the single-bin dispatcher. Reading
// `package.json` at runtime works under Node + npm but is fragile across
// resolution layouts (pnpm hoisting, npx temp dirs, the bundled tarball).
// Generating a TS constant at build time bakes the literal into the dist
// output — no runtime branching, no JSON-import-attribute gymnastics.
//
// Run via: `prepare` script (after pnpm install) AND `prepack` (before npm
// publish). Idempotent — overwrites only if version changes.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MCP_ROOT = join(__dirname, "..");
const PKG_PATH = join(MCP_ROOT, "package.json");
const VERSION_TS_PATH = join(MCP_ROOT, "src", "version.ts");

// src/ may not exist yet on first install — sibling CLI script gets away
// without mkdir because packages/cli/src/ pre-exists. Make this self-sufficient.
mkdirSync(dirname(VERSION_TS_PATH), { recursive: true });

const { version } = JSON.parse(readFileSync(PKG_PATH, "utf8"));

const banner =
  "// Generated by scripts/sync-version.mjs — do NOT edit by hand.\n// Source of truth: packages/mcp/package.json#version (Changesets-managed).\n";
const body = `export const VERSION = ${JSON.stringify(version)};\n`;
const next = banner + body;

let current = "";
try {
  current = readFileSync(VERSION_TS_PATH, "utf8");
} catch {
  // First run — file does not exist yet.
}

if (current !== next) {
  writeFileSync(VERSION_TS_PATH, next);
}
// Silent on success — runs on every install. Failure path would use
// console.error (writeFileSync throws and the process exits non-zero).
