#!/usr/bin/env node
// Generates packages/engine/src/version.ts from packages/engine/package.json.
//
// Why: ENGINE_VERSION is baked into scan output (the footer `engine vX` and the SARIF
// `tool.driver.version`). The engine is pure (D-28: no fs reads at runtime) and is bundled
// into the CLI binary via `bun build --compile`, so it can't read package.json at runtime —
// the version must be a literal compiled in at build time. Hand-maintaining it drifted
// (shipped 0.5.0 through the 0.5.x line). Generating it keeps it in lockstep automatically.
//
// Run via: `prepare` (after pnpm install) AND `prepack` (before npm publish) AND in CI
// before `bun build --compile` (release-binaries.yml). Idempotent.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENGINE_ROOT = join(__dirname, "..");
const PKG_PATH = join(ENGINE_ROOT, "package.json");
const VERSION_TS_PATH = join(ENGINE_ROOT, "src", "version.ts");

const { version } = JSON.parse(readFileSync(PKG_PATH, "utf8"));

const banner =
  "// Generated by scripts/sync-version.mjs — do NOT edit by hand.\n// Source of truth: packages/engine/package.json#version (Changesets-managed).\n";
const body = `export const ENGINE_VERSION = ${JSON.stringify(version)};\n`;
const next = banner + body;

let current = "";
try {
  current = readFileSync(VERSION_TS_PATH, "utf8");
} catch {
  // First run — file does not exist yet.
}

if (current !== next) {
  writeFileSync(VERSION_TS_PATH, next);
}
// Silent on success — runs on every install.
