import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ENGINE_VERSION } from "../src/index.js";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8")) as {
  version: string;
};

// D-05 drift gate (the long-intended "Plan 02-09" check). ENGINE_VERSION is baked into scan
// output (footer `engine vX`, SARIF tool.driver.version); it drifted to 0.5.0 across the whole
// 0.5.x line because nothing enforced it. version.ts is now generated by sync-version.mjs, and
// this test fails the build if the generated constant ever falls out of step with package.json.
describe("ENGINE_VERSION (D-05 drift gate)", () => {
  it("matches the version field in package.json (no drift)", () => {
    expect(ENGINE_VERSION).toBe(pkg.version);
  });

  it("is a valid semver MAJOR.MINOR.PATCH string", () => {
    expect(ENGINE_VERSION).toMatch(/^\d+\.\d+\.\d+(?:-[\w.-]+)?$/);
  });
});
