// D-33 provider evidence catalog. Single source of truth across engine routing, rule matchers,
// and Phase 11 leak-scanner (which reuses secret_literal_prefix). Adding a provider = minor bump
// of @hookwarden/rules; engine release not required (the catalog is data, not engine code).

import type { ProviderCatalog } from "@hookwarden/engine";

export const PROVIDER_CATALOG: ProviderCatalog = {
  stripe: {
    signature_header: ["stripe-signature"],
    sdk_packages: ["stripe", "@stripe/stripe-js"],
    sdk_verify_calls: [
      "webhooks.constructEvent",
      "Webhook.constructEvent",
      "Webhook.construct_event",
    ],
    secret_env_prefix: ["STRIPE_WEBHOOK", "STRIPE_SIGNING"],
    secret_literal_prefix: ["whsec_"],
    conventional_paths: [
      "/webhooks/stripe",
      "/api/webhooks/stripe",
      "/stripe/webhook",
      "/stripe/webhooks",
    ],
    hmac_algorithm: "sha256",
    signing_input_format: "raw_body",
    timestamp_header: null,
    signature_encoding: "hex",
    applicable_rules: [
      "missing-signature-verification",
      "timing-unsafe-comparison",
      "raw-body-misuse",
      "missing-timestamp-check",
      "wrong-hmac-algorithm",
      "unreachable-verification",
      "hardcoded-secret-prefix",
      "library-verified",
      "express-middleware-ordering",
    ],
  },
  github: {
    signature_header: ["x-hub-signature-256", "x-hub-signature"],
    sdk_packages: ["@octokit/webhooks", "@octokit/webhooks-methods"],
    sdk_verify_calls: ["verify", "verifyRequest"],
    secret_env_prefix: ["GITHUB_WEBHOOK", "GH_WEBHOOK"],
    secret_literal_prefix: ["ghs_", "github_pat_"],
    conventional_paths: [
      "/webhooks/github",
      "/api/webhooks/github",
      "/github/webhook",
      "/github/webhooks",
    ],
    hmac_algorithm: "sha256",
    signing_input_format: "raw_body",
    timestamp_header: null,
    signature_encoding: "hex",
    applicable_rules: [
      "missing-signature-verification",
      "timing-unsafe-comparison",
      "raw-body-misuse",
      "missing-timestamp-check",
      "missing-timing-safe-equal",
      "wrong-hmac-algorithm",
      "unreachable-verification",
      "hardcoded-secret-prefix",
      "library-verified",
    ],
  },
  shopify: {
    signature_header: ["x-shopify-hmac-sha256"],
    sdk_packages: ["@shopify/shopify-api", "@shopify/shopify-app-express"],
    sdk_verify_calls: [
      "verifyHmac",
      "webhookRegistry.process",
      "shopify.webhooks.validate",
      "verify",
    ],
    secret_env_prefix: ["SHOPIFY_WEBHOOK", "SHOPIFY_API_SECRET", "SHOPIFY_SIGNING"],
    secret_literal_prefix: [],
    conventional_paths: [
      "/webhooks/shopify",
      "/api/webhooks/shopify",
      "/shopify/webhook",
      "/shopify/webhooks",
      "/webhooks/orders/create",
      "/webhooks/products/update",
    ],
    hmac_algorithm: "sha256",
    signing_input_format: "raw_body",
    timestamp_header: null,
    signature_encoding: "base64",
    applicable_rules: [
      "missing-signature-verification",
      "timing-unsafe-comparison",
      "raw-body-misuse",
      "missing-timestamp-check",
      "wrong-hmac-algorithm",
      "unreachable-verification",
      "library-verified",
    ],
  },
  slack: {
    signature_header: ["x-slack-signature"],
    sdk_packages: ["@slack/bolt", "@slack/events-api", "@slack/webhook"],
    sdk_verify_calls: [
      "verifyRequestSignature",
      "isValidSlackRequest",
      "SignatureVerification",
      "verify",
      "is_valid_request",
    ],
    secret_env_prefix: ["SLACK_SIGNING", "SLACK_WEBHOOK"],
    secret_literal_prefix: [],
    conventional_paths: [
      "/webhooks/slack",
      "/api/webhooks/slack",
      "/slack/events",
      "/slack/commands",
      "/slack/interactivity",
      "/slack/options",
    ],
    hmac_algorithm: "sha256",
    signing_input_format: "timestamp_dot_body",
    timestamp_header: "x-slack-request-timestamp",
    signature_encoding: "hex",
    applicable_rules: [
      "missing-signature-verification",
      "timing-unsafe-comparison",
      "raw-body-misuse",
      "missing-timestamp-check",
      "wrong-hmac-algorithm",
      "unreachable-verification",
      "library-verified",
    ],
  },
  square: {
    signature_header: ["x-square-hmacsha256-signature"],
    sdk_packages: ["square", "squareup"],
    sdk_verify_calls: [
      "WebhooksHelper.verifySignature",
      "verifySignature",
      "WebhooksHelper.isValidWebhookEventSignature",
      "isValidWebhookEventSignature",
      "WebhooksHelper.is_valid_webhook_event_signature",
      "is_valid_webhook_event_signature",
    ],
    secret_env_prefix: ["SQUARE_WEBHOOK", "SQUARE_SIGNATURE_KEY"],
    secret_literal_prefix: [],
    conventional_paths: [
      "/webhooks/square",
      "/api/webhooks/square",
      "/square/webhook",
      "/square/webhooks",
    ],
    hmac_algorithm: "sha256",
    signing_input_format: "custom_field_tuple",
    timestamp_header: null,
    signature_encoding: "base64",
    applicable_rules: [
      "missing-signature-verification",
      "timing-unsafe-comparison",
      "raw-body-misuse",
      "wrong-hmac-algorithm",
      "unreachable-verification",
      "library-verified",
    ],
  },
  twilio: {
    signature_header: ["x-twilio-signature"],
    sdk_packages: ["twilio"],
    sdk_verify_calls: ["validateRequest", "RequestValidator.validate", "validate"],
    secret_env_prefix: ["TWILIO_AUTH", "TWILIO_SIGNING"],
    secret_literal_prefix: [],
    conventional_paths: [
      "/webhooks/twilio",
      "/api/webhooks/twilio",
      "/twilio/webhook",
      "/twilio/voice",
      "/twilio/sms",
      "/twilio/messaging",
    ],
    hmac_algorithm: "sha1",
    signing_input_format: "custom",
    timestamp_header: null,
    signature_encoding: "base64",
    applicable_rules: [
      "missing-signature-verification",
      "timing-unsafe-comparison",
      "raw-body-misuse",
      "missing-timestamp-check",
      "wrong-hmac-algorithm",
      "unreachable-verification",
      "library-verified",
    ],
  },
};
