#!/usr/bin/env node
// Generates packages/cli/src/version.ts from packages/cli/package.json.
//
// Why: The CLI exposes its version via citty's `meta.version`. Reading
// `package.json` at runtime via fs.readFileSync(import.meta.url + "/../..")
// works under Node + npm but fails inside Bun's `bun build --compile`
// standalone binary, where the source-tree path doesn't exist (Bun bundles
// into a virtual /$bunfs/ filesystem). Generating a TS constant at build
// time bakes the literal into the bundled output — works for both runtimes
// without runtime branching, no JSON-import-attribute / rootDir gymnastics.
//
// Run via: `prepare` script (after pnpm install) AND `prepack` (before npm
// publish) AND in CI before `bun build --compile` (release-binaries.yml).
// Idempotent — overwrites only if version changes.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLI_ROOT = join(__dirname, "..");
const PKG_PATH = join(CLI_ROOT, "package.json");
const VERSION_TS_PATH = join(CLI_ROOT, "src", "version.ts");

const { version } = JSON.parse(readFileSync(PKG_PATH, "utf8"));

const banner =
  "// Generated by scripts/sync-version.mjs — do NOT edit by hand.\n// Source of truth: packages/cli/package.json#version (Changesets-managed).\n";
const body = `export const VERSION = ${JSON.stringify(version)};\n`;
const next = banner + body;

let current = "";
try {
  current = readFileSync(VERSION_TS_PATH, "utf8");
} catch {
  // First run — file does not exist yet.
}

if (current !== next) {
  writeFileSync(VERSION_TS_PATH, next);
}
// Silent on success — runs on every install. Failure path would use
// console.error (writeFileSync throws and the process exits non-zero).
